"""Small reusable utilities for the vision XAI workshop notebooks."""

from .plotting import plot_bwr_attributions, show_image, show_image_grid
from .gradients import (
    cam,
    gradcam,
    gradient_magnitude,
    gradient_times_input,
    input_gradient,
    smoothgrad,
)
from .lrp import (
    explain_image,
    relevance_gap,
    setup_lrp,
)
from .perturbation import occlusion
from .spurious import (
    IMAGENET_W_CARTON_INDEX,
    IMAGENET_W_EXAMPLE_FILENAME,
    IMAGENET_W_EXAMPLE_WNID,
    add_imagenet_w_watermark,
    load_spurious_display_image_batch,
    load_watermark_example,
    load_watermarked_images,
    resolve_imagenet_w_example_path,
)
from .spray import (
    IMAGENETTE_WNID_TO_IMAGENET_INDEX,
    build_cluster_comparison_figure,
    build_clickable_spray_explorer,
    build_spectral_diagnostics_figure,
    cluster_heatmaps,
    compute_tsne_embedding,
    configure_resnet_for_spray_lrp,
    extract_dataset_lrp,
    get_spray_heatmaps,
    load_display_image_batch,
    load_spray_cache,
    make_spray_cohort,
    prepare_spray_features,
    run_kmeans_heatmap_baseline,
    run_spray_spectral_clustering,
    save_spray_cache,
    select_imagenette_class_samples,
    summarize_watermark_clusters,
)
from .vision import (
    get_imagenet_class_names,
    load_display_image,
    load_pretrained_resnet18,
    load_pretrained_vgg16,
    normalize_imagenet,
    predict_image_logits,
    predict_top_classes,
    resolve_imagenet_class_index,
    resolve_example_image_path,
)

__all__ = [
    "IMAGENETTE_WNID_TO_IMAGENET_INDEX",
    "IMAGENET_W_CARTON_INDEX",
    "IMAGENET_W_EXAMPLE_FILENAME",
    "IMAGENET_W_EXAMPLE_WNID",
    "add_imagenet_w_watermark",
    "cam",
    "build_cluster_comparison_figure",
    "build_clickable_spray_explorer",
    "build_spectral_diagnostics_figure",
    "cluster_heatmaps",
    "compute_tsne_embedding",
    "configure_resnet_for_spray_lrp",
    "extract_dataset_lrp",
    "explain_image",
    "get_imagenet_class_names",
    "get_spray_heatmaps",
    "gradcam",
    "gradient_magnitude",
    "gradient_times_input",
    "input_gradient",
    "load_display_image",
    "load_display_image_batch",
    "load_pretrained_resnet18",
    "load_pretrained_vgg16",
    "load_spray_cache",
    "load_spurious_display_image_batch",
    "load_watermark_example",
    "load_watermarked_images",
    "make_spray_cohort",
    "normalize_imagenet",
    "occlusion",
    "plot_bwr_attributions",
    "prepare_spray_features",
    "predict_image_logits",
    "predict_top_classes",
    "resolve_example_image_path",
    "resolve_imagenet_class_index",
    "resolve_imagenet_w_example_path",
    "relevance_gap",
    "run_kmeans_heatmap_baseline",
    "run_spray_spectral_clustering",
    "save_spray_cache",
    "select_imagenette_class_samples",
    "setup_lrp",
    "show_image",
    "show_image_grid",
    "smoothgrad",
    "summarize_watermark_clusters",
]
